DELIMITER $$
CREATE PROCEDURE TABLE_C
(
ID INT(10),
CARDNUMBER INT(10),
ISS VARCHAR(100),
ACQ VARCHAR(100),
DEST VARCHAR(100),
STATUS_A INT(10),
STATUS_ISS INT(10),
STATUS_ACQ INT(10),
STATSU_DEST INT(10)
)
BEGIN
INSERT INTO table_c
VALUES (ID, CARDNUMBER , ISS, ACQ, DEST, STATUS_A, STATUS_ISS,
STATUS_ACQ, STATSU_DEST );
END$$
DELIMITER ;